FROM samuelololol/ubuntu-codeviz-base:latest

ARG PYTHON_VERSION=3.7

RUN apt-get update && apt-get install -y --no-install-recommends \
build-essential cmake git curl wget ca-certificates && \
rm -rf /var/lib/apt/lists/*

RUN wget https://repo.continuum.io/miniconda/Miniconda3-4.7.12.1-Linux-x86_64.sh -O ~/miniconda.sh  && \
     chmod +x ~/miniconda.sh && \
     ~/miniconda.sh -b -p /opt/conda && \
     rm ~/miniconda.sh && \
     /opt/conda/bin/conda install -y python=$PYTHON_VERSION numpy pyyaml scipy ipython mkl mkl-include ninja cython typing\
      pytorch torchvision cudatoolkit=10.1 -c pytorch&& \
     /opt/conda/bin/conda clean -ya

ENV PATH /opt/conda/bin:$PATH

RUN pip install pandas gensim==3.8.3 scikit-learn==0.22.2.post1 cvxpy matplotlib tensorflow==1.13.1 keras==2.2.4 nltk==3.4.5 h5py==2.10.0 pytrec_eval pyltr

ENV TZ=America/New_York

RUN echo $TZ > /etc/timezone && \
apt-get install -y tzdata && \
rm /etc/localtime && \
ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
dpkg-reconfigure -f noninteractive tzdata

RUN apt-get autoremove -y && \
apt-get clean && \
rm -rf /var/lib/apt-lists/*