kafka:
    #build: .
    image: samuelololol/kafka
    environment:
        KAFKA_HEAP_OPTS: '-Xmx64M -Xms64M'
        KAFKA_ZOOKEEPER_CONNECT: 'zk1:2181,zk2:2181,zk3:2181'
        KAFKA_ADVERTISED_PORT: 9092
        KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    links:
        - zk1
        - zk2
        - zk3

zk1:
    image: samuelololol/zookeeper
    environment:
        MYID: 1

zk2:
    image: samuelololol/zookeeper
    environment:
        MYID: 2
        ZK: zk1
    links:
        - zk1

zk3:
    image: samuelololol/zookeeper
    environment:
        MYID: 3
        ZK: zk1
    links:
        - zk1

