zkm:
    image: samuelololol/zookeeper
    environment:
        MYID: 0
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock

zks:
    image: samuelololol/zookeeper
    environment:
        ZK: zkm
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    links:
        - zkm

